layout_spectrum: 0.7482044152077287
typography_spectrum: 0.6411141706018312
color:
  lightness: 0.9710251136113991
  brandColors:
    - '#F9E4AD'
    - '#E6B098'
    - '#CC4452'
    - '#723147'
    - '#31152B'
  saturation: 0.8296590970297076
  brandStrength: 0.8369750618526139
  rhythmicContrast: 0.30934494318818617
coverPrefs:
  filter: false
name: Stigmes
analytics: {}
github: true
author: {}
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
content: []
content_rating:
  adult: false
opengraph: {}
