layout_spectrum: 0.7475329041228362
typography_spectrum: 0.7600911008354535
color:
  lightness: 0.05146874778738043
  brandColors:
    - '#332532'
    - '#644D52'
    - '#F77A52'
    - '#FF974F'
    - '#A49A87'
  saturation: 0.0925589484329529
  brandStrength: 0.21377757021567165
  rhythmicContrast: 0.056703743167074015
coverPrefs:
  filter: false
name: Stigmes
analytics: {}
github: true
author: {}
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
content: []
content_rating:
  adult: false
opengraph: {}
