layout_spectrum: 0.4652713391343408
typography_spectrum: 0.19047707536469888
color:
  lightness: 0.9795011264012001
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  saturation: 0.027741595802847113
  brandStrength: 0.5963931223715074
  rhythmicContrast: 0.5035224526170825
coverPrefs:
  filter: false
name: Waters of Colonia
analytics: {}
github: true
author: {}
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
content: []
content_rating:
  adult: false
opengraph: {}
