name: Waters of Colonia
analytics: {}
github: true
author: {}
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
content: []
layout_spectrum: 0.548256644383995
color:
  lightness: 0.06648669625337392
  brandColors:
    - '#25064D'
    - '#36175E'
    - '#553285'
    - '#7B52AB'
    - '#9768D1'
  saturation: 0.5897844324139232
  brandStrength: 0.5812157219508202
  rhythmicContrast: 0.2885288423579186
content_rating:
  adult: false
typography_spectrum: 0.3910749404894944
opengraph: {}
