layout_spectrum: 0.691296320056432
typography_spectrum: 0.6954735246939713
color:
  lightness: 0.2568189832289694
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  saturation: 0.027748986615126234
  brandStrength: 0.5934689057138887
  rhythmicContrast: 0.2844757069969126
coverPrefs:
  filter: false
name: Waters of Colonia
analytics: {}
github: true
author: {}
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
content: []
content_rating:
  adult: false
opengraph: {}
