layout_spectrum: 0.7145166853861422
typography_spectrum: 0.08960064543604777
color:
  lightness: 0.9538976599485383
  brandColors:
    - '#6B0C22'
    - '#D9042B'
    - '#F4CB89'
    - '#588C8C'
    - '#011C26'
  saturation: 0.9223712601701701
  brandStrength: 0.7512276840977149
  rhythmicContrast: 0.26834070469049903
coverPrefs:
  filter: false
name: Stigmes
analytics: {}
github: true
author: {}
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
content: []
content_rating:
  adult: false
opengraph: {}
